[package]
name = "leaktk-scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
ring = "0.16"
clap = { version = "4.0", features = ["derive"] }
