# NOTE: This config file format is still in the draft stages and will likely
# change.
#
# All items in the config should have sane defaults and the
# config is optional.
#
# [logger]
#
# # Valid Values: "ERROR", "WARN", "INFO", "DEBUG", or "TRACE"
# level = "INFO"
#
# [scanner]
#
# How long a clone can take before it times out and is aborted (default: 0)
# # zero means no timeout.
# clone_timeout = 60
# # How many clones can happen at once
# clone_workers = 1
# # How many requests can sit in the clone queue before it blocks (default: 1)
# max_clone_queue_size = 1
# # The max depth the scanner will go back for things that have a version
# # history. If unset or set to zero there is no max scan depth.
# max_scan_depth = 256
# # How many requests can sit in the scan queue before it blocks (default: 1)
# max_scan_queue_size = 1
# # How many scans can happen at once
# scan_workers = 1
# # The full path to where the scanner should store files, clone repos, etc
# # for better performance mount a tmpfs at this location
# workdir = "/tmp/leaktk/scanner"
# # This defaults to ~/.cache/leaktk/scanner
#
# [scanner.patterns]
#
# # How often should the patterns be refreshed
# refresh_after = 43200
#
# [scanner.patterns.server]
#
# # The URL to a pattern server
# # The path "/patterns/{scanner}/{version}" will be appended to this URL
# url = "https://raw.githubusercontent.com/leaktk/patterns/main/target"
# # If this value is not set then the following sources will be checked in this order:
# #
# # 1) LEAKTK_PATTERN_SERVER_URL env var
# # 2) Fall back on "https://raw.githubusercontent.com/leaktk/patterns/main/target"
#
# # This defines the auth bearer token sent to the server.
# auth_token = "<insert auth token here>"
# # If auth_token is not set, the following sources will be checked in this order:
# #
# # 1) LEAKTK_PATTERN_SERVER_AUTH_TOKEN env var
# # 2) ~/.config/leaktk/pattern-server-auth-token
# #
# # If none of the above are defined, no Authorization header is sent to the pattern
# # server.
